In [1]:
import torch

In [2]:
a = torch.tensor([[0, 0, 1], [0, 0, 0], [-1, 0, 0]], dtype=torch.float32)
b = torch.tensor([[0, 1, 0], [-1, 0, 0], [0, 0, 0]], dtype=torch.float32)
c = torch.tensor([[0, 0, 0], [0, 0, 1], [0, -1, 0]], dtype=torch.float32)
print(a)
print(b)
print(c)

tensor([[ 0.,  0.,  1.],
        [ 0.,  0.,  0.],
        [-1.,  0.,  0.]])
tensor([[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0.,  0.]])
tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]])


In [3]:
torch.det(a)

tensor(0.)

In [12]:
A = torch.matrix_exp(a)
B = torch.matrix_exp(b)
C = torch.matrix_exp(c)
print(torch.matmul(A, torch.t(A)))
print(torch.matmul(B, torch.t(B)))
print(torch.matmul(C, torch.t(C)))

tensor([[1.0000e+00, 0.0000e+00, 1.2824e-10],
        [0.0000e+00, 1.0000e+00, 0.0000e+00],
        [1.2824e-10, 0.0000e+00, 1.0000e+00]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.0000, 1.0000, 0.0000],
        [0.0000, 0.0000, 1.0000]])
tensor([[1.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.0000e+00, 1.2824e-10],
        [0.0000e+00, 1.2824e-10, 1.0000e+00]])


In [18]:
def commute(x, y):
    return torch.matmul(x, y) - torch.matmul(y, x)

In [23]:
commute(a, b) # == c
commute(a, c) # == b
commute(b, c) # == a

tensor([[ 0.,  0.,  1.],
        [ 0.,  0.,  0.],
        [-1.,  0.,  0.]])

In [25]:
def exp(x):
    return torch.matrix_exp(x)

In [28]:
exp(3 * a)

tensor([[-0.9900,  0.0000,  0.1411],
        [ 0.0000,  1.0000,  0.0000],
        [-0.1411,  0.0000, -0.9900]])

In [27]:
exp(a)

tensor([[ 0.5403,  0.0000,  0.8415],
        [ 0.0000,  1.0000,  0.0000],
        [-0.8415,  0.0000,  0.5403]])